[package]
name = "python-project-generator"
version = "1.5.2"
edition = "2021"
authors = ["Paul Sanders <paul@paulsanders.dev>"]
description = "Generates a Python project structure."
documentation = "https://github.com/sanders41/python-project-generator"
homepage = "https://github.com/sanders41/python-project-generator"
repository = "https://github.com/sanders41/python-project-generator"
readme = "README.md"
keywords = ["cli", "python", "template"]
categories = ["command-line-utilities"]
license = "MIT"

[[bin]]
name = "python-project"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.84"
clap = { version = "4.5.15", features = ["color", "suggestions", "derive"] }
colored = "2.0.4"
dirs = "5.0.1"
indicatif = "0.17.8"
minijinja = "2.2.0"
rayon = "1.10.0"
reqwest = { version = "0.12.7", features = ["json", "blocking"] }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.126"
time = { version = "0.3.35", features = ["local-offset"] }

[dev-dependencies]
insta = { version = "1.39.0", features = ["yaml"] }
tempfile = "3.12.0"
