[package]
name = "python-project-generator"
version = "1.0.9"
edition = "2021"
authors = ["Paul Sanders <psanders1@gmail.com>"]
description = "Generates a Python project structure."
documentation = "https://github.com/sanders41/python-project-generator"
homepage = "https://github.com/sanders41/python-project-generator"
repository = "https://github.com/sanders41/python-project-generator"
readme = "README.md"
keywords = ["cli", "python", "template"]
categories = ["command-line-utilities"]
license = "MIT"

[[bin]]
name = "python-project"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.78"
clap = { version = "4.4.18", features = ["color", "suggestions", "derive"] }
colored = "2.0.4"
dirs = "5.0.1"
indicatif = "0.17.7"
minijinja = "1.0.12"
reqwest = { version = "0.11.22", features = ["json", "blocking"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
time = { version = "0.3.29", features = ["local-offset"] }

[dev-dependencies]
tempfile = "3.9.0"
