[package]
name = "python-project-generator"
version = "0.1.0"
edition = "2021"
authors = ["Paul Sanders <psanders1@gmail.com>"]
description = "Generates a Python project structure."
documentation = "https://github.com/sanders41/python-project-generator"
homepage = "https://github.com/sanders41/python-project-generator"
repository = "https://github.com/sanders41/python-project-generator"
readme = "README.md"
keywords = ["cli", "python", "template"]
categories = ["command-line-utilities"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.2", features = ["color", "suggestions", "derive"] }
colored = "2.0.4"
indicatif = "0.17.6"
minijinja = "1.0.7"
reqwest = { version = "0.11.20", features = ["json", "blocking"] }
serde_json = "1.0.105"
