[package]
name = "python-project-generator"
version = "1.0.31"
edition = "2021"
authors = ["Paul Sanders <psanders1@gmail.com>"]
description = "Generates a Python project structure."
documentation = "https://github.com/sanders41/python-project-generator"
homepage = "https://github.com/sanders41/python-project-generator"
repository = "https://github.com/sanders41/python-project-generator"
readme = "README.md"
keywords = ["cli", "python", "template"]
categories = ["command-line-utilities"]
license = "MIT"

[[bin]]
name = "python-project"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.3", features = ["color", "suggestions", "derive"] }
colored = "2.0.4"
dirs = "5.0.1"
indicatif = "0.17.8"
minijinja = "2.0.1"
rayon = "1.10.0"
reqwest = { version = "0.12.4", features = ["json", "blocking"] }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.115"
time = { version = "0.3.35", features = ["local-offset"] }

[dev-dependencies]
tempfile = "3.10.1"
