on:
  release:
    types:
      - published

name: Publish binaries to release

jobs:
  publish:
    name: Publish for ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: python-project
            asset_name: python-project-generator-linux-amd64
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            artifact_name: python-project
            asset_name: python-project-generator-macos-amd64
            target: x86_64-apple-darwin
          - os: macos-latest
            artifact_name: python-project
            asset_name: python-project-generator-macos-aarch64
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN}}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
